### ISSUE TITLE
Quest: Alas,Andorhal (Western Plaguelands)

### ISSUE THREAD

**Issue by BugTestR** [darrowshire-dev/bugtracker#284]
Issue: When killing Araj the Summoner (61) elite he will drop his phylactery and only 1 player in the group is able to loot it and take it and then it disappears.

How it should work : At the very least all 5 members should be able to loot the phylactery. I've seen people do raids and still able to get people to loot it so more than 5 people that I know of are able to loot it.

**Comment by ratkosrb** [comment]
This commit should resolve the issue https://github.com/vmangos/core/commit/eef543dc1346c35b731ca7f3f9e8bd31bc58b73b

**Comment by BugTestR** [comment]
Tried the quest today and still only 1 person is able to loot, I've seen multiple groups able to loot this.

**Comment by BugTestR** [comment]
Bump, quest isn't fixed still only 1 person able to loot it and the respawn time on the elite is 10 min. or more
